-- DROP SCRIPT --
DROP TABLE IF EXISTS MUSIC_ALBUM;
DROP TABLE IF EXISTS MUSIC_ARTIST;
DROP TABLE IF EXISTS MUSIC_LABEL;
DROP TABLE IF EXISTS MUSIC_FORMAT;
DROP TABLE IF EXISTS MUSIC_GENRE;

-- CREATE TABLE SCRIPT --
CREATE TABLE MUSIC_ARTIST
(
ARTIST_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
ARTIST_NAME VARCHAR(100),
ORIGIN_CITY VARCHAR(100),
GENRE_NAME VARCHAR(7),
CONSTRAINT MUSIC_ARTIST_GENRE_NAME CHECK (GENRE_NAME IN ("Rock", "Jazz", "Pop", "Hip Hop", "Country"))
);

CREATE TABLE MUSIC_LABEL
(
LABEL_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
LABEL_NAME VARCHAR(75)
);

CREATE TABLE MUSIC_FORMAT
(
FORMAT_ID CHAR(1) PRIMARY KEY,
FORMAT_NAME VARCHAR(50)
);

CREATE TABLE MUSIC_ALBUM
(
ALBUM_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
ALBUM_NAME VARCHAR(100),
ARTIST_ID INT,
RELEASE_DATE DATE,
RECORDS_SOLD INT(8),
ORIGINAL_FORMAT CHAR(1),
LABEL_ID INT,
CONSTRAINT MUSIC_ALBUM_ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES MUSIC_ARTIST(ARTIST_ID),
CONSTRAINT MUSIC_ALBUM_ORIGINAL_FORMAT_FK FOREIGN KEY (ORIGINAL_FORMAT) REFERENCES MUSIC_FORMAT(FORMAT_ID),
CONSTRAINT MUSIC_ALBUM_LABEL_ID_FK FOREIGN KEY(LABEL_ID) REFERENCES MUSIC_LABEL(LABEL_ID)
);

ALTER TABLE MUSIC_ARTIST AUTO_INCREMENT = 2;
ALTER TABLE MUSIC_LABEL AUTO_INCREMENT = 2;
ALTER TABLE MUSIC_ALBUM AUTO_INCREMENT = 2;

-- INSERT DATE SCRIP -- 
-- inserting values into music artist -- 
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME) VALUES ("Nirvana", "Seattle, WA", "Rock");
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME) VALUES ("Miles Davis", "Alton, IL", "Jazz");
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME) VALUES ("Micheal Jackson", "Gary, IN", "Pop");
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME) VALUES ("Lil' Wayne", "New Orleans, LA", "Hip Hop");
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME) VALUES ("Willie Nelson", "Abbot, TX", "Country");

-- inserting values into music label --
INSERT INTO MUSIC_LABEL(LABEL_NAME) VALUES ("DGC Record");
INSERT INTO MUSIC_LABEL(LABEL_NAME) VALUES ("Columbia");
INSERT INTO MUSIC_LABEL(LABEL_NAME) VALUES ("Epic Records");
INSERT INTO MUSIC_LABEL(LABEL_NAME) VALUES ("Cash Money");

-- inserting values into music format --
INSERT INTO MUSIC_FORMAT VALUES ("V", "Vynyl");
INSERT INTO MUSIC_FORMAT VALUES ("T", "Cassette Tape");
INSERT INTO MUSIC_FORMAT VALUES ("C", "Compact Disc");
INSERT INTO MUSIC_FORMAT VALUES ("D", "Digital");

-- inserting values into music album --
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("Nevermind", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 2), STR_TO_DATE("23-SEP-91", "%d-%b-%Y"), 30000000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'C'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 2));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("In Utero", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 2), STR_TO_DATE("21-SEP-93", "%d-%M-%Y"), 15000000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'C'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 2));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("Kind of Blue", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 3), STR_TO_DATE("17-AUG-59", "%d-%M-%Y"), 4000000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'V'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 3));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("Thriller", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 4), STR_TO_DATE("30-NOV-82", "%d-%M-%Y"), 65000000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'T'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 4));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("Bad", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 4), STR_TO_DATE("1-SEP-87", "%d-%M-%Y"), 45000000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'T'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 4));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("The Carter III", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 5), STR_TO_DATE("9-JUN-08", "%d-%M-%Y"), 3800000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'D'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 5));
INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID) VALUES
	("Red Headed Stranger", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_ID = 6), STR_TO_DATE("1-MAY-75", "%d-%M-%Y"), 200000, 
		(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_ID = 'V'), (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_ID = 3));


-- MODIFY SCRIPT -- 
-- creating table music_genre ---
CREATE TABLE MUSIC_GENRE
(
GENRE_ID CHAR(1) PRIMARY KEY,
GENRE_NAME VARCHAR(25)
);

-- inserting the dat present in table above --
INSERT INTO MUSIC_GENRE VALUES ("R", "Rock");
INSERT INTO MUSIC_GENRE VALUES ("P", "Pop");
INSERT INTO MUSIC_GENRE VALUES ("J", "Jazz");
INSERT INTO MUSIC_GENRE VALUES ("C", "Country");
INSERT INTO MUSIC_GENRE VALUES ("H", "Hip Hop");

-- replacing genre_name field in the music_artist tabel with genre_id
ALTER TABLE MUSIC_ARTIST
ADD GENRE_ID CHAR(1);

-- updating the genre data in the music_artist table
UPDATE  MUSIC_ARTIST 
SET GENRE_ID = (
				SELECT DISTINCT GENRE_ID 
				FROM MUSIC_GENRE
				WHERE GENRE_NAME = MUSIC_ARTIST.GENRE_NAME
                );
                

ALTER TABLE MUSIC_ARTIST
ADD CONSTRAINT MUSIC_ARTIST_GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES MUSIC_GENRE(GENRE_ID);

ALTER TABLE MUSIC_ARTIST
DROP CONSTRAINT MUSIC_ARTIST_GENRE_NAME;

ALTER TABLE MUSIC_ARTIST
DROP COLUMN GENRE_NAME;

-- getting rid of the artist Lil' Wayne and all of his albums --
DELETE FROM MUSIC_ALBUM
WHERE ARTIST_ID = (
				SELECT ARTIST_ID
				FROM MUSIC_ARTIST
				WHERE ARTIST_NAME = "Lil' Wayne"
                );
			
DELETE FROM MUSIC_ARTIST
WHERE ARTIST_NAME = "Lil' Wayne";

